### ISSUE TITLE
chat messages auto-sending

### ISSUE THREAD

**Issue by Cube-from-Blender** [astra1dev/AUnlocker#25] opened 2024-08-26 21:45 UTC
Randomly when im chatting, it auto-sends i have no idea why this happens, if you could fix this bug it would help not make me look like an idiot, thanks

im playing on the latest version of AUnlocker on the latest update

**Comment by astra1dev** [comment] 2024-08-27 09:25
I have had this issue myself. 
However, resolving this might require some more testing. If you have any more details on when and why this occurs exactly, please let me know.

**Comment by astra1dev** [comment] 2024-08-27 17:43
Possible. Could you try setting `ChatPatches` in the file `[your-among-us-location]/BepInEx/AUnlocker.cfg` to `false`?

**Comment by Cube-from-Blender** [comment] 2024-08-29 06:07
@astra1dev i decided to do that, and it doesn't auto-send anymore, so its definetly one of the Chat Patches

**Comment by astra1dev** [comment] 2024-08-29 06:11
Alright thank you. I will do some more testing on what exactly is causing this and then publish a new version with the fix and maybe some new features. Have a nice day 😄

**Comment by astra1dev** [comment] 2024-08-30 23:58
I found the bug and will fix it in the next update.

for anyone interested, the issue is that in ChatPatches.cs the characters: newline (\n) and carriage return (\r) are not forbidden
```cs
public static bool Prefix(TextBoxTMP __instance, char i, ref bool __result)
    {
        if (AUnlocker.PatchChat.Value)
        { 
            __result = !(i == '\b');    // this caused the OP's issue, 
                                        // checks for \r and \n will be added next update 
            return false;
        }
        else return true;
    }
```

**Comment by astra1dev** [comment] 2024-09-07 08:33
Closing as [v1.1.7 ](https://github.com/astra1dev/AUnlocker/releases/tag/v1.1.7) fixes this.

**Closed by astra1dev** 2024-09-07 08:33 UTC
Labels: type: bug

**Comment by redphantom1000** [comment] 2024-09-07 11:13
So return symbols can no longer be typed in chat? Nice. I had this issue when using aunlocker on TOHE lobbies and being unable to use commands witbout clicking the send button instead of enter. Temporarily resolved by turning off chat patches

**Comment by astra1dev** [comment] 2024-09-07 11:32
Yes, with v1.1.7 you should be able to use tohe commands with ChatPatches enabled

**Comment by redphantom1000** [comment] 2024-09-07 11:33
Thanks
