### ISSUE TITLE
a new update for among us is out...

### ISSUE THREAD

**Issue by Vermax104** [astra1dev/AUnlocker#8] opened 2024-04-02 21:48 UTC

**Comment by astra1dev** [comment] 2024-04-02 21:53
ok and?

**Comment by Vermax104** [comment] 2024-04-02 22:34
I just wanted you to be aware, after the update, all the cosmetics disappeared from the inventory :(, I had to reinstall the game, I loved the unlocker, waiting for updates, ty!

**Comment by astra1dev** [comment] 2024-04-02 22:36
Yes, AUnlocker does not unlock the cosmetics permanently. If you remove the mod, the cosmetics are gone. 
Please download and install the latest AUnlocker version and see if it works for you.

**Comment by Vermax104** [comment] 2024-04-02 22:54
not working after new update, Before that it was working perfectly.
![Captura de tela 2024-04-02 195028](https://github.com/astra1dev/AUnlocker/assets/130305426/50bc81d7-aff6-419c-82a6-015425a86685)

**Comment by astra1dev** [comment] 2024-06-18 16:55
can you try now? new among us update is out

**Comment by astra1dev** [comment] 2024-08-14 20:54
Closing as this is a duplicate of https://github.com/astra1dev/AUnlocker/issues/22 which was already fixed

**Closed** 2024-08-14 20:54 UTC
Labels: type: bug, duplicate
